version: '3.9'

services:
  node:
    build: ./docker/node
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app:cached
    command: sh -c "yarn start"
    ports:
      - "3000:3000"

